"""phase2_bhavcopy_daily

Revision ID: 06e34d247fdc
Revises: b2c3d4e5f6a7
Create Date: 2026-05-27 18:50:42.950915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e34d247fdc'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bhavcopy_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('sym', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tottrdval', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'sym')
    )
    op.create_index('idx_bhavcopy_date', 'bhavcopy_daily', ['date'], unique=False)
    op.create_index('idx_bhavcopy_sym_date', 'bhavcopy_daily', ['sym', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bhavcopy_sym_date', table_name='bhavcopy_daily')
    op.drop_index('idx_bhavcopy_date', table_name='bhavcopy_daily')
    op.drop_table('bhavcopy_daily')
    # ### end Alembic commands ###
